### ISSUE TITLE
Yandex layers TileSchema

### ISSUE THREAD

**Issue by LeffBA** [ArcBruTile/ArcBruTile#10]
TileSchema for Yandex layers in the current release defined incorrectly. The scheme should be used spatial reference system EPSG:3395 (WorldMercator), instead of EPSG:3857 (WebMercator).
![srs-shift_3857-3395](https://cloud.githubusercontent.com/assets/12054209/22108536/a31f63c2-de64-11e6-8830-54cbaf08dbd0.png)

Something like this:
```C#
public class YandexSchema : SphericalMercatorWorldSchema
{
    public YandexSchema()
    {
        Name = "YandexMaps";
        Format = "png";
        Axis = AxisDirection.InvertedY;
        OriginY = -OriginY;
        Srs = "EPSG:3395";
    }
}
```

**Comment by bertt** [comment]
Hi, I've looked at it but it was not so easy to fix, maybe I will try again if still needed

**Comment by LeffBA** [comment]
I may not see the full picture, but the above code fixed the bug for me.

**Comment by bertt** [comment]
ah ok I'll try again

**Comment by bertt** [comment]
your change looks like this?
https://github.com/ArcBruTile/ArcBruTile/commit/786b1519ea325ca6c4934a874eaefe1861a66828

will be in next release 0.9 if working

**Comment by LeffBA** [comment]
Yes, the shift between layers is fixed.
