### ISSUE TITLE
Support for ArcMap 10.5

### ISSUE THREAD

**Issue by wvcpw** [ArcBruTile/ArcBruTile#11]
Is ArcBru Tile being updated to support ArcMap 10.5?  Currently I get this error: 
`System.Net.WebException: The remote server returned an error: (404) Not Found.`

**Comment by bertt** [comment]
Yes should work alright. I think it's related to Dropbox dropping support for webserver (15/3).
What version of ArcBrutile you have installed? Can you post last error messages of the ArcBruTile log file? On which action you got this error?

**Comment by bertt** [comment]
I've created release 0.8, can you install and test it?
https://github.com/ArcBruTile/ArcBruTile/releases/tag/0.8

**Comment by bertt** [comment]
issue should be fixed, so closing this issue. If not reopen again.
