### ISSUE TITLE
Not working in ArcMap 10.3

### ISSUE THREAD

**Issue by pichiciego** [ArcBruTile/ArcBruTile#12]
I just installed ArcBru Tile 0.7 in ArcMap 10.3 and the only services that are working are OSM and Bing. The other services give the following error:
![image](https://cloud.githubusercontent.com/assets/27689972/25092063/0829b792-235a-11e7-918b-77afca396fdd.png).

The Add TMS service function is also not working. Any idea what could be the problem? Thank you.

**Comment by bertt** [comment]
Hi, I think it's because Dropbox webserver functionality stopped working. I'll check this week.

**Comment by pichiciego** [comment]
Great. Thank you!

**Comment by bertt** [comment]
I've created release 0.8, can you install and test it?
https://github.com/ArcBruTile/ArcBruTile/releases/tag/0.8

**Comment by pichiciego** [comment]
Thank you very much! It appears to be working fine now. There are some services (MapBox) though that are still not working. They get added to the table of contents, but not displayed. No error message either. 
Thanks again.

**Comment by bertt** [comment]
ok great its working again, for the mapbox service can you give it another try?

**Comment by pichiciego** [comment]
I just tried the mapbox service again and the only one that appears to be working is the Satellite map. The MapQuest is also not working, but an error window is popping up stating "Parameter is not valid".

**Comment by bertt** [comment]
- MapQuest seems to have have discontinued support for direct tile access (https://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/). I think I'll remove it in next release;
- MapBox should work, can you post last part of your log file? (C:\Users\{your_username_here}\AppData\Local\ArcBruTile\ArcBruTile.log).

**Comment by bertt** [comment]
see https://github.com/ArcBruTile/ArcBruTile/issues/13 for MapQuest issue

**Comment by pichiciego** [comment]
Sorry, I cannot find/access the ArcBruTile.log file. Probably because I don't have administrator rights on this computer (work computer). I can try it on my personal computer later today and let you know.

**Comment by bertt** [comment]
okay

**Comment by pichiciego** [comment]
Attached is the log file (converted to txt because Github would not let me upload a .log file). I found it in another drive. I hope it is helpful. Cheers.

[ArcBruTile.txt](https://github.com/ArcBruTile/ArcBruTile/files/929909/ArcBruTile.txt)

**Comment by bertt** [comment]
ok thanks,
. mapbox: you still use an old access key somehow, maybe wait some time or restart arcmap. You can delete the log file, a new one will be created
. stamen: i see an error about stamen tile (something with https) for example http://c.tile.stamen.com/terrain-background/12/1306/2437.jpg

**Comment by pichiciego** [comment]
Thanks. I closed ArcMap, deleted the log file and then restarted, and mapbox is working fine now. Stamen is also working fine, so I don't understand why it was giving an error message.

**Comment by bertt** [comment]
ok great! Closing this issue.

**Comment by bradernaufal** [comment]
https://github.com/ArcBruTile/ArcBruTile/releases/tag/0.8 

Excusme sir, this link was eror. Is there another link again? Thks

**Comment by bertt** [comment]
@bradernaufal https://bertt.itch.io/arcbrutile
