### ISSUE TITLE
Trying to add a TMS

### ISSUE THREAD

**Issue by timkeane** [ArcBruTile/ArcBruTile#14]
I work for NYC and am publishing a TMS using GeoServer/GWC.  I am having issues getting ArcBruTile to load the service into ArcMap and was hoping someone might give me a hand.

https://maps.nyc.gov/tms/1.0.0/
https://maps.nyc.gov/tms/1.0.0/catrto/basemap/service.xml

**Comment by bertt** [comment]
Hi, whats the issue you have?

**Comment by timkeane** [comment]
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
  at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
  at System.Uri..ctor(String uriString)
  at BruTile.Tms.TileMapParser.CreateTileSource(Stream tileMapResource, String overrideUrl, Dictionary`2 customParameters, IPersistentCache`1 persistentCache, Func`2 fetchTile)
  at BruTileArcGIS.Lib.ConfigTms.CreateTileSource()
  at BruTileArcGIS.Lib.BruTileLayer.InitializeLayer()
  at BruTileArcGIS.Lib.BruTileLayer..ctor(Iapplication app, EnumBruTileLayer enumBruTileLayer, String tmsUrl, Boolean overwriteUrls, String auth)
  at BruTileArcGIS.Lib.commands.AddServiceCommand.OnCLick()

**Comment by bertt** [comment]
I think there are a couple of issues:

- In https://maps.nyc.gov/tms/1.0.0/ most links (tilemap - href) don't work
- In https://maps.nyc.gov/tms/1.0.0/catrto/basemap/service.xml the TileMap - href is not correct

It should look like the MapBox files, for example:
https://github.com/ArcBruTile/ArcBruTile/blob/master/config/Services/Mapbox/Mapbox.xml
and https://github.com/ArcBruTile/ArcBruTile/blob/master/config/Services/Mapbox/Satellite.xml

Are you able to edit those href elements?

**Comment by timkeane** [comment]
brett-

thanks for taking the time... someone else was supposed to take care of this for a presentation tomorrow and didn't so i am trying to nail it down.  I was basing my xml files on the OSM service.

"In https://maps.nyc.gov/tms/1.0.0/ most links (tilemap - href) don't work" - what do you mean exactly?

from https://maps.nyc.gov/tms/1.0.0/
```
...
<TileMap title="basemap" srs="EPSG:900913" profile="global-mercator" href="https://maps.nyc.gov/tms/1.0.0/catrto/basemap/service.xml"/>
...
```

and from https://maps.nyc.gov/tms/1.0.0/catrto/basemap/service.xml

```
<TileMap version="1.0.0" tilemapservice="http://tms.osgeo.org/1.0.0">
	<Title>NYC Basemap</Title>
	<Abstract/>
	<SRS>EPSG:900913</SRS>
	<BoundingBox minx="-20037508.34" miny="-20037508.34" maxx="20037508.34" maxy="20037508.34"/>
	<Origin x="-20037508.34" y="-20037508.34"/>
	<TileFormat width="256" height="256" mime-type="image/jpeg" extension="jpg"/>
	<TileSets>
		<TileSet href="8" units-per-pixel="611.4962261962891" order="0"/>
		<TileSet href="9" units-per-pixel="305.74811309814453" order="1"/>
		<TileSet href="10" units-per-pixel="152.87405654907226" order="2"/>
		<TileSet href="11" units-per-pixel="76.43702827453613" order="3"/>
		<TileSet href="12" units-per-pixel="38.218514137268066" order="4"/>
		<TileSet href="13" units-per-pixel="19.109257068634033" order="5"/>
		<TileSet href="14" units-per-pixel="9.554628534317017" order="6"/>
		<TileSet href="15" units-per-pixel="4.777314267158508" order="7"/>
		<TileSet href="16" units-per-pixel="2.388657133579254" order="8"/>
		<TileSet href="17" units-per-pixel="1.194328566789627" order="9"/>
		<TileSet href="18" units-per-pixel="0.5971642833948135" order="10"/>
		<TileSet href="19" units-per-pixel="0.2985821416974068" order="11"/>
		<TileSet href="20" units-per-pixel="0.1492910708487034" order="12"/>
		<TileSet href="21" units-per-pixel="0.0746455354243517" order="13"/>
	</TileSets>
</TileMap>
```

Some of the TileMap hrefs were not up when i first started this thread - but basmap was - the rest are all there now too

**Comment by timkeane** [comment]
i see that i am missing an href attribute in the TileSet elements of https://maps.nyc.gov/tms/1.0.0/catrto/basemap/service.xml

going to fix that up and try again

**Comment by bertt** [comment]
file  https://maps.nyc.gov/tms/1.0.0/ looks better now, links are working

**Comment by bertt** [comment]
tip: when debugging this issue the log file is quite useful. Default location: C:\Users\{your_username_here}\AppData\Local\ArcBruTile\ArcBruTile.log

It contains all the requests and responses for tiles, so you can see whats going on.

**Comment by timkeane** [comment]
i have been looking at it, but the errors i were getting were before request could be initiated and were not being logged.  is there away to bump up log level so i can see the debug output from BruTileLayer.cs?

**Comment by timkeane** [comment]
i am seeing the requests now, but the urls are invalid

https://maps.nyc.gov/tms/1.0.0/catrto/basemap/service.xml/0/185/222.jpg

current service description URLs
https://maps.nyc.gov/tms/1.0.0/
https://maps.nyc.gov/tms/1.0.0/catrto/basemap/service.xml

**Comment by bertt** [comment]
can you add overwriteurls="false" to https://maps.nyc.gov/tms/1.0.0/ ?

example:
<TileMap title="basemap" srs="EPSG:900913" profile="global-mercator" overwriteurls="false" href="https://maps.nyc.gov/tms/1.0.0/catrto/basemap/service.xml"/>

**Comment by timkeane** [comment]
trying now... takes a few b/c i have to copy to multiple servers and invalidate file at cdn

**Comment by bertt** [comment]
ok I have to go now, can look again tomorrow. 

If you have a working tile url you want to show that will be helpfull, something like
https://maps.nyc.gov/tms/1.0.0/catrto/basemap/9/151/323.jpg (gives 404 now)

good luck :-)

**Comment by timkeane** [comment]
i am also assuming that i need type="" since when using my TMS in openlayers i do so with ```{-y}``` as follow:

```
var baseLayer = new ol.layer.Tile({
  extent: [-8453323, 4774561, -7983695, 5165920],
  source: new ol.source.XYZ({
    url: 'https://maps{1-4}.nyc.gov/tms/1.0.0/carto/basemap/{z}/{x}/{-y}.jpg'
  })
});```

and btw... ArcBruTile is a very nice project... it's rare to find esri projects where people have even heard of unit tests... i starred you guys

**Comment by timkeane** [comment]
you can view a working use of the service here: https://maps.nyc.gov/tiles/show.html

here is a working tile: https://maps.nyc.gov/tms/1.0.0/carto/basemap/10/303/640.jpg

**Comment by timkeane** [comment]
i got it... thanks so much for helping out!

**Comment by bertt** [comment]
ok great its working! 
I've added Neww York City Maps to list of providers https://github.com/ArcBruTile/ArcBruTile/commit/d51244fe44f442f6bf29298e35b94beedb45a475 so people can select from list instead of typing url

![nyc](https://cloud.githubusercontent.com/assets/538812/25371692/38ca7a38-2992-11e7-97e7-acb61a70f6d2.png)

Closing this issue now.

**Comment by timkeane** [comment]
Bert-
I am happy to have you include our TMS in your plugin, but it us currently in a softlaunch and has yet to be announced. Can you remove for now?  I will absolutely give you a heads up when we make a public announcement. 
-Tim
-------- Original message --------From: Bert Temme <notifications@github.com> Date: 4/25/17  2:36 AM  (GMT-05:00) To: ArcBruTile/ArcBruTile <ArcBruTile@noreply.github.com> Cc: Tim Keane <t.d.keane@gmail.com>, Author <author@noreply.github.com> Subject: Re: [ArcBruTile/ArcBruTile] Trying to add a TMS (#14) 
ok great its working!

I've added Neww York City Maps to list of providers d51244f so people can select from list instead of typing url

Closing this issue now.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ArcBruTile/ArcBruTile","title":"ArcBruTile/ArcBruTile","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ArcBruTile/ArcBruTile"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bertt in #14: ok great its working! \r\nI've added Neww York City Maps to list of providers https://github.com/ArcBruTile/ArcBruTile/commit/d51244fe44f442f6bf29298e35b94beedb45a475 so people can select from list instead of typing url\r\n\r\n![nyc](https://cloud.githubusercontent.com/assets/538812/25371692/38ca7a38-2992-11e7-97e7-acb61a70f6d2.png)\r\n\r\nClosing this issue now."}],"action":{"name":"View Issue","url":"https://github.com/ArcBruTile/ArcBruTile/issues/14#issuecomment-296929097"}}}

**Comment by bertt** [comment]
yes sure its removed

**Comment by timkeane** [comment]
Thanks again Bert... presentation went well.

as i said i will give you a heads up when the TMS is announced.

I was also hoping maybe we might figure out why my TMS label images render
so poorly in ArcMap - they look great in QGIS.  Those images are png8,
don't know if that's an issue.  If you point me in the right place I can
give it a look, although I long ago gave up on writing code with ESRI APIs.

https://maps.nyc.gov/tms/1.0.0/
https://maps.nyc.gov/tms/1.0.0/carto/label/service.xml


[image: Inline image 2]
[image: Inline image 1]

**Comment by timkeane** [comment]
not sure those attachments came through so posting them here as well

![qgis](https://cloud.githubusercontent.com/assets/8377998/25398495/537d6e26-29ba-11e7-8294-650d668ee3e1.png)

![arcgis](https://cloud.githubusercontent.com/assets/8377998/25398501/59e6c4ce-29ba-11e7-86c2-232c2e37eb52.png)

**Comment by bertt** [comment]
yes that looks quite messy :-(
Improving this will involve playing with the code at https://github.com/ArcBruTile/ArcBruTile/blob/master/trunk/ArcBruTile/app/lib/BruTileHelper.cs#L169
But most of the time its a lot of trial and error work to get good performance and quality rendering for the various image formats.

**Comment by bertt** [comment]
Just took a quick look: its related to reprojection of tiles going on. Labels look good when I have the Data Frame - Coordinate System set to WGS_1984_Web_Mercator (Wkid=3785)

![labels](https://cloud.githubusercontent.com/assets/538812/25419867/84407c60-2a55-11e7-8a6e-3944571b4cf9.png)

**Comment by timkeane** [comment]
I thought i was doing that. I will try again.
-------- Original message --------From: Bert Temme <notifications@github.com> Date: 4/26/17  1:54 AM  (GMT-05:00) To: ArcBruTile/ArcBruTile <ArcBruTile@noreply.github.com> Cc: Tim Keane <t.d.keane@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [ArcBruTile/ArcBruTile] Trying to add a TMS (#14) 
Just took a quick look: its related to reprojection of tiles going on. Labels look good when I have the Data Frame - Coordinate System set to WGS_1984_Web_Mercator (Wkid=3785)


—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ArcBruTile/ArcBruTile","title":"ArcBruTile/ArcBruTile","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ArcBruTile/ArcBruTile"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bertt in #14: Just took a quick look: its related to reprojection of tiles going on. Labels look good when I have the Data Frame - Coordinate System set to WGS_1984_Web_Mercator (Wkid=3785)\r\n\r\n![labels](https://cloud.githubusercontent.com/assets/538812/25419867/84407c60-2a55-11e7-8a6e-3944571b4cf9.png)\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/ArcBruTile/ArcBruTile/issues/14#issuecomment-297245389"}}}

**Comment by timkeane** [comment]
Bert-

I have been setting the dataframe to EPSG:3857.  I'm not much of an arcmap jockey... do you have a .prj I can use to import Coordinate System set to WGS_1984_Web_Mercator (Wkid=3785)?

also is that srs deprecated? http://epsg.io/3785

the TMS is EPSG:900913 which is the geoserver default and it thought that was equivalent to EPSG:3857

**Comment by bertt** [comment]
Hi Tim, yes there seems to be an conversion between 900913 to 3785 going on, maybe some legacy thing? 

Anyways you can also try to use 3857 in the TMS  XML files, like in the Richland configs (https://github.com/ArcBruTile/ArcBruTile/tree/master/config/Services/Richland) - note I don't know if those services still work

**Comment by timkeane** [comment]
i did just that (switched the tms desc to 3857) and it works

**Comment by timkeane** [comment]
Bert-
We still haven't had a formal launch, but I've tired of waiting on the folks responsible for that.  The TMS is in use and I've added XYZ and WMTS endpoints as well.  If you'd like to build our service into you default config, please go ahead.  Specs are here: https://maps.nyc.gov/tiles/
-Tim

**Comment by bertt** [comment]
Ok its added again, https://github.com/ArcBruTile/ArcBruTile/commit/8d2818bdf074dfcc096bd242afab95ebf40ccdde

People can select now the New York City Maps from the 'Add TMS Provider' dialog instead of typing the url.
