### ISSUE TITLE
tianditu offset

### ISSUE THREAD

**Issue by MagicWang** [ArcBruTile/ArcBruTile#15]
I'm using this tool load tianditu.The coordinates has offset a lot.I have seen tianditu wmts use 96 dpi,but arcgis use 90 dpi.How to solve?

**Comment by MagicWang** [comment]
![qq 20170826140641](https://user-images.githubusercontent.com/3860039/29739079-d04ef038-8a67-11e7-9f7e-a56390b7a26c.jpg)

**Comment by bertt** [comment]
for Tianditu standard ArcMap WMTS functionality is used. 
Do you have the same problem when adding http://t0.tianditu.com/vec_c/wmts?request=GetCapabilities&service=wmts ? (http://desktop.arcgis.com/en/arcmap/10.3/map/web-maps-and-services/adding-wmts-services.htm)

**Comment by MagicWang** [comment]
yes,but how to solve

**Comment by bertt** [comment]
then it might be an issue in ArcMap, can you try it in ArcGIS Pro?

**Comment by MagicWang** [comment]
same as ArcMap

**Comment by bertt** [comment]
maybe projection issue? Tianditu uses epsg:4490 (China Geodetic Coordinate System 2000),

**Comment by MagicWang** [comment]
no，cgcs2000 most the same with wgs84 for civil use.

**Comment by bertt** [comment]
since it's an standard ArcMap issue better ask Esri about this.
