### ISSUE TITLE
Can i still using the 0.8 ArcBruTile version.

### ISSUE THREAD

**Issue by iamrknowhow** [ArcBruTile/ArcBruTile#17]
Hello,

I am a teacher from college and for many years i been using your amazing ArcBruTile tool in my classes. I still using the 0.8 versión and i saw that now, that versión is not available for download by my students. My question is about if i can still using the 0.8 versión in my college or if i need a new license for use. 

Thanks for being build this kind or good tools for ArcGIS users.

**Comment by bertt** [comment]
Hi thanks, no the 0.8 download is no longer available.
