### ISSUE TITLE
Don't work Yandex Layers in ArcBruTile 1.0

### ISSUE THREAD

**Issue by DocFoUkS** [ArcBruTile/ArcBruTile#19]
Hello! 2 days ago a can't use Yandex layers (Streets, Satellite, Hybrid). I click on any Yandex maps link and it don't show in Table of Contents and on map.  ArcMap 10.1
Video how it working
https://www.dropbox.com/s/i0dmtppil70e0f9/Screencast%202018-02-02.mp4?dl=0

**Comment by bertt** [comment]
it's fixed in ArcBruTile 1.0.2

**Comment by DocFoUkS** [comment]
And how can download it? I will have to buy it?

**Comment by bertt** [comment]
yep https://bertt.itch.io/arcbrutile

**Comment by DocFoUkS** [comment]
Ok. Thnx

**Comment by bertt** [comment]
👍
