### ISSUE TITLE
How I can add XYZ Tile Layers in ArcBruTile 1.0.2. ?

### ISSUE THREAD

**Issue by DocFoUkS** [ArcBruTile/ArcBruTile#20]
Hello! I want to add my custom link with XYZ tile layer in ArcMap. I prepare XML-scheme and load in ArcBruTile from Add TMS service... 
But map is not draw( Can you send a small instruction how work with custom TMS services?

**Comment by bertt** [comment]
Hi, can you share the XML file(s)? 

tip: when debugging this issue the log file is quite useful. Default location: C:\Users{your_username_here}\AppData\Local\ArcBruTile\ArcBruTile.log

It contains all the requests and responses for tiles, so you can see whats going on.

**Comment by DocFoUkS** [comment]
So test XML
https://raw.githubusercontent.com/DocFoUkS/GABT/master/Google_Test
Fnd want to show
https://raw.githubusercontent.com/DocFoUkS/GABT/master/Google_road.xml
Worked link is https://mt1.google.com/vt/lyrs=m&x={x}&y={y}&z={z}
I looked log files) Thnx)

**Comment by bertt** [comment]
sorry cannot assist with this, had to remove google support because legal reasons
