### ISSUE TITLE
Can this support custom xyz layer services??

### ISSUE THREAD

**Issue by yh371174229** [ArcBruTile/ArcBruTile#24]
I want to add my xyz layer service,like http://192.168.90.110:8099/u101/{z}/{x}/{y}/tile.png.
Is there a way to add this service to ArcMap by ArcBruTile??
Any Help will appreciated！

**Comment by bertt** [comment]
Hi yes this is possible, by creating a service file (something like https://raw.githubusercontent.com/ArcBruTile/ArcBruTile/master/configuration/Services/osm/hot.xml) and a provider file (like https://raw.githubusercontent.com/ArcBruTile/ArcBruTile/master/configuration/Services/osm/osm.xml)  and put them on a webserver.  Layer(s) can be added via ArcBruTile -> Add TMS Service...

**Comment by yh371174229** [comment]
Thank you very much,I'll try it.
