### ISSUE TITLE
not enough memory

### ISSUE THREAD

**Issue by yh371174229** [ArcBruTile/ArcBruTile#25]
ArcEngine10.4.1
1.add my coustom xyz service layer
2.As the map moves, the memory becomes larger.
3.then the app will crash
This exception fires in `DrawRasterNew ` function
Is there a good way to solove it?? AnyHelp will appreciated！

![image](https://user-images.githubusercontent.com/5948456/51309517-91280a80-1a7f-11e9-9bc9-018907737a32.png)

**Comment by bertt** [comment]
ArcBruTile has moved on to a private repository since a year so cannot help with this.

**Comment by yh371174229** [comment]
ok,get it.
Thanks again!
