### ISSUE TITLE
Layers will not hold in arc

### ISSUE THREAD

**Issue by Jedwards157** [ArcBruTile/ArcBruTile#26]
The layers will not hold in arcgis when the template is closed. Each layer has to be readded by hand each time a template is opened.

**Comment by bertt** [comment]
can reproduce this in ArcMap 10.4.1 (by load layer -> save mxd -> close arcmap -> open mxd -> layer is missing).
Thought this has worked before so maybe something is broken.

**Comment by bertt** [comment]
"ESRI Premium Support Services have confirmed that the PersistenceHelperClass has been deprecated as of AGD10.4.x. Persisting data to the mxd is no longer supported.
Solution is to design something custom to persist object data yourself." 

https://gis.stackexchange.com/questions/229103/persistence-in-arcobjects-10-4-back-to-ipersistvariant/252738

**Comment by bertt** [comment]
found a fix for most mapservices, will be in next release
