### ISSUE TITLE
XML definition files hosting 

### ISSUE THREAD

**Issue by tramponi** [ArcBruTile/ArcBruTile#4]
Why not hosting the XML definition files somewhere else than dropbox?

Dropbox access is usually restricted in several workplaces, expecially if you are not using the HTTPS protocol.

**Comment by bertt** [comment]
ok thanks, I'll consider to move them to another place (preferably this Github repro)

**Comment by bertt** [comment]
fixed in next release 0.8, config files are now on Github https://github.com/ArcBruTile/ArcBruTile/tree/master/config
