### ISSUE TITLE
BruTile.Desktop.dll could not be found	

### ISSUE THREAD

**Issue by yang9tn** [ArcBruTile/ArcBruTile#6]
Thanks for your remarkable work. But when I try to compile it with VS2015, report shows ArcBruTileSetup\ArcBruTileSetup.vdproj can't be supported and BruTile.Desktop.dll could not be found	when rebuild.

**Comment by bertt** [comment]
Hi thanks, for building setups you need to install something extra: https://visualstudiogallery.msdn.microsoft.com/f1cc3f3e-c300-40a7-8797-c509fb8933b9

**Comment by bertt** [comment]
for the  BruTile.Desktop.dll  try to rebuild the project BruTile.Desktop separate (it's in the solution)

**Comment by yang9tn** [comment]
thanks, it works.

**Comment by bertt** [comment]
ok great :-)
