### ISSUE TITLE
Publish by NuGet

### ISSUE THREAD

**Issue by karavanjo** [ArcBruTile/ArcBruTile#8]
@bertt how about this?

**Comment by bertt** [comment]
you mean a NuGet package with ArcBruTile functionality? Is possible but I doubt there is enough interest to justify the time to be spend on this.

**Comment by karavanjo** [comment]
Thank you for the answer. I use ArcBruTile in my project and I need to add the library as a .dll into the source code of the project, as it may be unavailable in developer's system. This problem can be solved by NuGet package. But may be only me need it, you're right :) The issue can be closed.

**Comment by bertt** [comment]
ah yes I understand your case. If we get more requests for NuGet package we can reconsider it, closing for now.
