### ISSUE TITLE
Exception from HRESULT:0x80041018

### ISSUE THREAD

**Issue by hoogw** [ArcBruTile/ArcBruTile#9]
I have arcMap 10, with this plugin, tool box installed. 

everytime when I zoom or pan map, I got popup error Exception from HRESULT:0x80041018

Please advise.

**Comment by bertt** [comment]
wild guess: something goes wrong with generating temporary rasters in your profile directory. What's is the ArcBruTile log file saying? (c:\Users\{name}\AppData\Local\ArcBruTile\ArcBruTile.log)

**Comment by bertt** [comment]
closed because no reaction
